spring.application.name=ms-pagamentos
spring.jackson.serialization.write-dates-as-timestamps=false

messaging.kafka.topics.pagar=pagar
messaging.kafka.topics.comprovante-gerado=comprovante.gerado.topic
spring.kafka.consumer.group-id=ms-pagamentos

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
