spring.application.name=ms-pagamentos
spring.jackson.serialization.write-dates-as-timestamps=false

messaging.kafka.topics.pagar=pagar
messaging.kafka.topics.comprovante-gerado=comprovante.gerado.topic

management.endpoints.web.exposure.include=health,info,prometheus
