CREATE DATABASE IF NOT EXISTS db_auth;
CREATE DATABASE IF NOT EXISTS db_faturas;
CREATE DATABASE IF NOT EXISTS db_pagamentos;
CREATE DATABASE IF NOT EXISTS db_comprovantes;
CREATE DATABASE IF NOT EXISTS db_backoffice;
