FROM maven:3.9.9-eclipse-temurin-21 AS build

ARG APP_MODULE
WORKDIR /workspace

COPY . .
RUN chmod +x mvnw && ./mvnw -pl ${APP_MODULE} -am package -DskipTests

FROM eclipse-temurin:21-jre-jammy

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

ARG APP_MODULE
WORKDIR /app

COPY --from=build /workspace/${APP_MODULE}/target/*.jar /app/app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
