spring.application.name=ms-notificacoes
spring.kafka.consumer.group-id=ms-notificacoes
messaging.kafka.topics.comprovante-gerado=comprovante.gerado.topic
messaging.kafka.topics.comprovante-gerado-dlt=comprovante.gerado.DLT
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
