spring.application.name=ms-backoffice
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3307/db_backoffice
spring.datasource.username=root
spring.datasource.password=root
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/db_backoffice

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=ms-backoffice
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
messaging.kafka.topics.problema-fatura=problema-fatura-routing

management.endpoints.web.exposure.include=health,info,prometheus
