global:
  scrape_interval: 15s

scrape_configs:
  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-gateway:8080"]
  - job_name: ms-faturas
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["ms-faturas:8081"]
  - job_name: ms-pagamentos
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["ms-pagamentos:8082"]
  - job_name: ms-comprovantes
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["ms-comprovantes:8083"]
  - job_name: ms-notificacoes
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["ms-notificacoes:8084"]
  - job_name: ms-backoffice
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["ms-backoffice:8085"]
